sonar.organization=nirina2108
sonar.projectKey=nirina2108_skillhub-front
sonar.projectName=SkillHub — Frontend React

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=**/tests/**,**/*.test.js,**/*.test.jsx

sonar.sourceEncoding=UTF-8
