sonar.organization=poun-2108
sonar.projectKey=poun-2108_skillhub-front
sonar.projectName=SkillHub - Frontend React

sonar.sources=src
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.coverage.exclusions=**/*.test.js,**/*.test.jsx,**/tests/**,src/components/**,src/pages/**,src/context/**,src/main.jsx,src/App.jsx

sonar.sourceEncoding=UTF-8
